version: '3.4'

services:
  delivery_api:
    expose:
      - 5000
      - 5001
    ports:
      - 9000:5000
      - 9001:5001
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Cert_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Cert_File}
    build:
      context: WizardEmporium.Delivery/
      dockerfile: Dockerfile
    volumes:
      - ${Cert_Path_From}:${Cert_Path_To}

  gateway_api:
    expose:
      - 5000
      - 5001
    ports:
      - 9002:5000
      - 9003:5001
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Cert_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Cert_File}
    build:
      context: WizardEmporium.Gateway/
      dockerfile: Dockerfile
    volumes:
      - ${Cert_Path_From}:${Cert_Path_To}

  store_api:
    expose:
      - 5000
      - 5001
    ports:
      - 9004:5000
      - 9005:5001
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Cert_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Cert_File}
    build:
      context: WizardEmporium.Store/
      dockerfile: Dockerfile
    volumes:
      - ${Cert_Path_From}:${Cert_Path_To}

  user_api:
    expose:
      - 5000
      - 5001
    ports:
      - 9006:5000
      - 9007:5001
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Cert_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Cert_File}
    build:
      context: WizardEmporium.User/
      dockerfile: Dockerfile
    volumes:
      - ${Cert_Path_From}:${Cert_Path_To}