version: '3.4'

services:
  delivery-api:
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Cert_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Cert_File}
    build:
      context: .
      dockerfile: WizardEmporium.Delivery/Dockerfile
    volumes:
      - ${Cert_Path_From}:${Cert_Path_To}

  store-api:
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Cert_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Cert_File}
    build:
      context: .
      dockerfile: WizardEmporium.Store/Dockerfile
    volumes:
      - ${Cert_Path_From}:${Cert_Path_To}

  user-api:
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Cert_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Cert_File}
    build:
      context: .
      dockerfile: WizardEmporium.User/Dockerfile
    volumes:
      - ${Cert_Path_From}:${Cert_Path_To}

  gateway-api:
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Cert_Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Cert_File}
    build:
      context: .
      dockerfile: WizardEmporium.Gateway/Dockerfile
    depends_on:
      - store-api
      - delivery-api
      - user-api
    volumes:
      - ${Cert_Path_From}:${Cert_Path_To}